### ISSUE TITLE
Colors suddenly overwritten

### ISSUE THREAD

**Issue by Thypari** [HamidMosalla/VisualStudio-ColorCoder#13]
So when I open a new document like a .cs file for the first time, it shows the correct colors. But 1s later it's all overwritten. 
This just happened today. I was using the extension fine for the last months.
I am using Microsoft Visual Studio Professional 2019 Version 16.6.3.

I deactivated all extension except for Color Coder and the issue persists.

The weird thing is the Overwriting also changes other text properties like boldness.

![correct](https://user-images.githubusercontent.com/9956801/86804425-33262300-c077-11ea-8c8b-818f4fca19e2.png)
![wrong](https://user-images.githubusercontent.com/9956801/86804440-36211380-c077-11ea-856f-d6138768e379.png)

**Comment by HamidMosalla** [comment]
I couldn't reproduce the issue on the latest version of visual studio with the latest version of the extension on a dark theme. Could you please send me this specific file or a project if you can so I can take a look? Maybe there's a specific textual element that causes this. Is this happens across all of your projects?

**Comment by Thypari** [comment]
I think it has something to do with logging into your Microsoft Account, so the cloud settings are pulled and they somehow start overwriting the color coder settings. I logged in on multiple different VMs, and suddenly I had the issue. 

I now imported my saved VS settings and everything is working again.

**Comment by HamidMosalla** [comment]
Glad to hear that.
