### ISSUE TITLE
Not compatible with VS 15.7

### ISSUE THREAD

**Issue by laicasaane** [HamidMosalla/VisualStudio-ColorCoder#2]
Hi, the extension is broken in VS 15.7. It cannot color methods, local variables, fields/properties, parameters anymore. The color of preprocessors is messed up: for example if #if are inside or next to other element, the symbol will be the same color as that other element.

**Comment by iMobCoding** [comment]
I can confirm, latest VS v15.7 update, broke the extension

**Comment by HamidMosalla** [comment]
Thanks for your feedback.

**Comment by laicasaane** [comment]
Sadly, this happens to every extensions that rely on Roslyn.

**Comment by HamidMosalla** [comment]
Fixed with version 1.0.1 release.
