### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by rdefulio** [HamidMosalla/VisualStudio-ColorCoder#6]
This is a great extension!  Do you think it is possible to override general editor text editor colors as well?  I have been struggling with trying to customize a color theme and I seem to run unfixable color issues with some elements, and I wonder if an extension like this could work around those problems.  

Thanks

Ron

**Comment by HamidMosalla** [comment]
What exactly are you trying to change the color of? It this extension can only change the color of listed constructs, but it can be extended if you know what ``ClassifiedSpan`` a part of text belong to.

**Comment by rdefulio** [comment]
Specifically I am trying to customize the color of a breakpointed line in the environment.  This is probably outside the scope of this extension but I was wondering if you had any thoughts on if you think it's possible with the API, and if so what API I should look at. Thanks for any advice you might have.

**Comment by HamidMosalla** [comment]
@rdefulio I'm not sure you could do that with Roslyn API, what's used in this extension analyze words. Every word belong to a group, I test to see the current word is of some kind, and if it is, color it. I suggest you take a look at [VSSDK-Extensibility-Samples](https://github.com/Microsoft/VSSDK-Extensibility-Samples), you might find something close to what you're looking for.
