### ISSUE TITLE
No color on generic methods

### ISSUE THREAD

**Issue by laicasaane** [HamidMosalla/VisualStudio-ColorCoder#7]
![image](https://user-images.githubusercontent.com/1594982/40487753-53373bd4-5f8f-11e8-99d5-3f78f0373f3e.png)

**Comment by HamidMosalla** [comment]
Can you tell me what version of Visual Studio you're using? Coloring for generic methods work on my machine (VS 15.7):
![untitled](https://user-images.githubusercontent.com/11329074/40488738-b46b9da4-5f7c-11e8-91f2-0caefbe9f700.png)
Another thing, when you press couple of enters, does generic GetControl's color change?

**Comment by laicasaane** [comment]
I'm using VS 15.7.2. When I press Enters, there is no change at all.

**Comment by laicasaane** [comment]
This bug happens when I use generic type as the return type.
![image](https://user-images.githubusercontent.com/1594982/40519574-6a2bbdd2-5fea-11e8-8275-62a906fa3d41.png)

**Comment by laicasaane** [comment]
I've just noticed another problem now: parameters of generic methods won't be colored too!

**Comment by HamidMosalla** [comment]
Fix in #10
