### ISSUE TITLE
Not working on VS2015

### ISSUE THREAD

**Issue by ArseniySavin** [HamidMosalla/VisualStudio-ColorCoder#8]
When I try set settings for code in setting VS. My VS fall with error.
In the Log event I see this:
Application: devenv.exe Framework Version: v4.0.30319 Description: The process  was terminated due to an unhandled exception. Exception Info:  System.Runtime.InteropServices.COMException at  System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32,  IntPtr) at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32, Int32[]) at  ColorCoder.ColorCoderCore.ColorManager.Load(System.String[]) at  ColorCoder.ChangeColorOptionGrid.LoadSettingsFromStorage() at  Microsoft.VisualStudio.Shell.DialogPage.OnClosed(System.EventArgs) at  Microsoft.VisualStudio.Shell.DialogPage+DialogSubclass.WndProc(System.Windows.Forms.Message  ByRef) at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32,  IntPtr, IntPtr)
--

**Comment by ArseniySavin** [comment]
I try debugging and resolve on my self. But i have not VS 2017 now.

**Comment by HamidMosalla** [comment]
Just use the previous version and prevent it from updating:
https://github.com/HamidMosalla/VisualStudio-ColorCoder/releases/download/v1.0/ColorCoder.vsix
I'll look into this issue for the next patch release.

**Comment by ArseniySavin** [comment]
Hamid, thanks you. It's worked. Best, useful and simple extension.
